
server:
  port: 9000

spring:
  jpa:
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/apigateway?useSSL=false
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
      routes:
        - id: customer-service
          uri: http://localhost:8080/
          predicates:
            - Path=/customers/**, /reviews/**, /credit-cards/**, /address/**

        - id: product-service
          uri: http://localhost:8181/
          predicates:
            - Path=/products/**

        - id: shopping-cart-service
          uri: http://localhost:8282/
          predicates:
            - Path=/carts/**

jwt-credentials:
  secret-key: the secret of jwt
  message: Login Success!!
